### ISSUE TITLE
Correct repository paths in package.json

### ISSUE THREAD

**Issue by nint8835** [MUNComputerScienceSociety/CSS-Slackbot2017#3]
At the moment, all URLs in package.json related to the repository (repository.url, bugs.url, and homepage) point to Moustafa's fork of the project, not the central project owned by the society.

**Comment by moustafaelsisy** [comment]
Hey Riley! Well spotted, thanks for notifying us. As this is a minor issue, I will take care of it myself. Please let us know if you do find any other problems or have any feedback that you would like to share. 😄
